### ISSUE TITLE
Add fixed scales for diff plots

### ISSUE THREAD

**Issue by evanoffPNNL** [JGCRI/metis#87] opened 2019-08-09 13:47 UTC
If possible, it would be helpful to be able to have a different, or fixed scale of some nature for when the diffOn = T in the metis.mapProcess function call. What is happening now is that the diff plots are using the original scale parameters used to calculate the scale for all of the plots, however the difference data sets are usually far different and may require a different type of scale to view properly.

**Comment by zarrarkhan** [comment] 2019-08-09 14:07
Note: This will apply to when the 'scaleRange' parameter in the metis.mapsProcess.R function is active (i.e. not NULL). When this is active map scales for kmeans and pretty legends are forced to the limits set in scaleRange. The problem is as Jason points out above that the same range is applied to the diff plots for the parameters indicated. We discussed this and a solution is to have a separate scaleRangeDiff option for each parameter.

**Comment by zarrarkhan** [comment] 2020-05-29 01:54
Addressed in pull requests #187

**Closed** 2020-05-29 01:54 UTC
Labels: enhancement
